require 'rails/generators'
require 'buildybuild/version'
require 'haml-rails'
require 'decent_exposure'
require 'rdiscount'
require 'formal'
require 'generators/buildybuild/cms/cms_generator'
require 'generators/buildybuild/active_link/active_link_generator'
